### ISSUE TITLE
EBS tagging fails with error below

### ISSUE THREAD

**Issue by binnythomas-1989** [sergiorua/kube-tagger#8]
Error:
Cannot find EBS volme associated with : resource name may not be empty

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
    volume.beta.kubernetes.io/aws-block-storage-additional-resource-tags: map_migrated=xxxxx,map-migrated-app=xxxxx
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```
